version: '3.8'

services:
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: point_management
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3309:3306"

  application:
    image: gentlemj/point-management-system:latest
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3309/point_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - database